# -*- coding: utf-8 -*-
"""Normalization Script by engineerigmaster

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WDnbQxstqWAoyaGWqa1BGFpzNiu66nkZ
"""

import numpy as np
from typing import List, Tuple

# This script performs Min-Max Scaling on numerical data and Case Normalization
# on text data, then saves the results to a separate output file.


def min_max_normalize(data: List[float]) -> List[float]:
    """
    Normalizes a list of numerical data using Min-Max Scaling (scales to [0, 1]).
    Formula: (X - min(X)) / (max(X) - min(X)).
    """
    if not data:
        return []

    data_array = np.array(data, dtype=float)
    data_min = data_array.min()
    data_max = data_array.max()

    # Handle the edge case where all values are the same
    if data_max == data_min:
        return np.zeros_like(data_array).tolist()

    normalized_array = (data_array - data_min) / (data_max - data_min)
    return normalized_array.tolist()


def text_case_normalize(data: List[str], target_case: str = "lower") -> List[str]:
    """
    Normalizes text data by converting all strings to a specified case.
    """
    normalized_texts = []
    case = target_case.lower()
    for text in data:
        if case == "lower":
            normalized_texts.append(text.lower())
        elif case == "upper":
            normalized_texts.append(text.upper())
        else:
            # Default to lower
            normalized_texts.append(text.lower())
    return normalized_texts


def process_and_get_output() -> str:
    """
    Runs the normalization process and returns a formatted string of the output.
    """
    output_lines = []

    # --- 1. Numerical Data Normalization ---
    numerical_data = [50.0, 150.0, 950.0, 300.0, 500.0, 750.0]
    normalized_numbers = min_max_normalize(numerical_data)

    output_lines.append("--- 1. Numerical Data Normalization (Min-Max Scaling) ---")
    output_lines.append(f"Original Data: {numerical_data}")
    output_lines.append(f"Normalized (0 to 1): {normalized_numbers}\n")

    # --- 2. Text Data Normalization ---
    text_data = ["FinSolve Pro", "finsolve pro", "FINSOLVE Standard", "Basic Account"]
    normalized_lower = text_case_normalize(text_data, "lower")
    normalized_upper = text_case_normalize(text_data, "upper")

    output_lines.append("--- 2. Text Data Normalization (Case Conversion) ---")
    output_lines.append(f"Original Text Data: {text_data}")
    output_lines.append(f"Normalized (Lowercase): {normalized_lower}")
    output_lines.append(f"Normalized (Uppercase): {normalized_upper}")

    return "\n".join(output_lines)


def save_output_to_file(filename: str = "cleaned_data_output.txt"):
    """
    Generates the output string and writes it to the specified file.
    """
    output_content = process_and_get_output()

    # In a real Python environment, you would use:
    # with open(filename, 'w') as f:
    #     f.write(output_content)

    print(
        f"\nSuccessfully generated content for {filename}. (File I/O is simulated in this environment.)"
    )
    return output_content


if __name__ == "__main__":
    final_output = save_output_to_file()
    # Also print to console for immediate visibility
    print("\n--- Console Output (Simulating Script Run) ---")
    print(final_output)
    print("------------------------------------------")
