# -*- coding: utf-8 -*-
"""Vector DB  1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cxidy7ZlCtuJrIjS7vm6WFYceGccqBuz
"""

!pip install chromadb
import chromadb
from chromadb.utils import embedding_functions

doc_content = """
# Quarterly Financial Report - FinSolve Technologies Inc. 2024

## Executive Summary
In 2024, FinSolve Technologies Inc. delivered exceptional financial performance, achieving significant year-over-year (YoY) growth across all quarters. With a strategic focus on market expansion, customer acquisition, and operational efficiency, the company saw revenue increase from $2.1 billion in Q1 to $2.6 billion in Q4, alongside consistent improvements in gross margin, operating income, and net income. This report provides a comprehensive overview of FinSolve Technologies’s financial results, expense breakdowns, cash flow analyses, and risk mitigation strategies for each quarter of 2024, underscoring our commitment to sustainable growth and shareholder value.

---

## Q1 - January to March 2024

### Quarterly Financial Overview
Q1 2024 set a strong foundation for the year, with robust revenue growth and operational efficiency. Key financial highlights include:

- **Revenue**: $2.1 billion, up 22% YoY, driven by strong customer acquisition and increased transaction volumes.
- **Gross Margin**: 58%, reflecting effective cost management and pricing strategies.
- **Operating Income**: $500 million, supported by streamlined operations and high-margin product offerings.
- **Net Income**: $250 million, up 10% YoY, bolstered by revenue growth and operational efficiencies.
- **Marketing Spend**: $500 million, focused on digital marketing campaigns and brand awareness initiatives to support European market entry.
- **Vendor Costs**: $120 million, driven by increased marketing activities and employee training programs.
... [Remaining Q1, Q2, Q3, Q4 details] ...
### Cash Flow Analysis
Cash flow performance supported long-term growth:
- **Cash Flow from Operations**: $450 million, up 18% YoY, driven by strong holiday sales and efficient working capital management.
- **Cash Flow from Investing**: $80 million, allocated to product enhancements and global expansion.
- **Cash Flow from Financing**: $35 million, securing funds for sustained growth in 2025.

---

## 2024 Annual Summary
FinSolve Technologies Inc. Inc. achieved remarkable financial results in 2024, with total revenue of $9.4 billion, a 28% YoY increase. Gross margin improved from 58% in Q1 to 64% in Q4, reflecting enhanced pricing strategies and operational efficiencies. Net income grew to $1.15 billion, up 14% YoY, driven by consistent revenue growth and cost discipline. Marketing spend totaled $2.3 billion, supporting global expansion and customer acquisition, while vendor costs rose modestly to $510 million due to strategic investments in regional campaigns and loyalty programs.

Cash flow from operations reached $1.5 billion, up 14% YoY, enabling $260 million in investments for R&D, market expansion, and product development. Financing activities provided $110 million to support working capital and long-term growth. Despite risks such as vendor cost inflation and competitive pressures, proactive mitigation strategies ensured financial stability and positioned FinSolve Technologies for continued success in 2025.

## Recommendations for 2025
1. **Optimize Marketing ROI**: Leverage data analytics to refine influencer and digital marketing strategies, ensuring higher returns on ad spend.
2. **Expand Cost Controls**: Continue vendor negotiations and explore automation to reduce operational and vendor costs.
3. **Accelerate Global Expansion**: Increase investment in high-growth regions like Southeast Asia and Latin America to sustain revenue growth.
4. **Enhance Cash Flow Management**: Further streamline accounts receivable processes to reduce DSO and improve liquidity.

## Conclusion
FinSolve Technologies Inc.’s 2024 performance reflects our strategic focus on growth, efficiency, and customer-centric innovation. With record-breaking revenue, improved margins, and strong cash flow, we are well-positioned to capitalize on global opportunities in 2025. This report highlights our commitment to delivering value to stakeholders while navigating market challenges with agility and foresight.
"""

chunks = []
metadatas_new = []

main_splits = doc_content.split('---')

if len(main_splits) > 0:
    executive_summary_content = main_splits[0].strip()
    if executive_summary_content:
        chunks.append(executive_summary_content)
        metadatas_new.append({'source': 'quarterly_financial_report.md', 'department': 'FinSolve Technologies Inc.', 'section': 'Executive Summary'})

if len(main_splits) > 1:
    q1_full_block = main_splits[1].strip()
    if q1_full_block:
        chunks.append(q1_full_block)
        metadatas_new.append({'source': 'quarterly_financial_report.md', 'department': 'FinSolve Technologies Inc.', 'section': 'Q1 (includes placeholder for Q2-Q4)'})

if len(main_splits) > 2:
    annual_and_beyond_block = main_splits[2].strip()

    temp_chunks = []
    temp_metadatas = []

    annual_parts = annual_and_beyond_block.split('## Recommendations for 2025', 1)
    if len(annual_parts) > 0:
        annual_summary_segment = annual_parts[0].split('## 2024 Annual Summary', 1)
        if len(annual_summary_segment) > 1 and annual_summary_segment[1].strip():
            temp_chunks.append("## 2024 Annual Summary\n" + annual_summary_segment[1].strip()) # Include header for clarity
            temp_metadatas.append({'source': 'quarterly_financial_report.md', 'department': 'FinSolve Technologies Inc.', 'section': 'Annual Summary'})
        elif annual_summary_segment[0].strip() and "## 2024 Annual Summary" in annual_summary_segment[0]:
             temp_chunks.append(annual_summary_segment[0].strip())
             temp_metadatas.append({'source': 'quarterly_financial_report.md', 'department': 'FinSolve Technologies Inc.', 'section': 'Annual Summary'})


    recs_and_conclusion_segment = annual_parts[1] if len(annual_parts) > 1 else ""
    recs_parts = recs_and_conclusion_segment.split('## Conclusion', 1)
    if len(recs_parts) > 0:
        recommendations_segment = recs_parts[0].split('## Recommendations for 2025', 1)
        if len(recommendations_segment) > 1 and recommendations_segment[1].strip():
            temp_chunks.append("## Recommendations for 2025\n" + recommendations_segment[1].strip())
            temp_metadatas.append({'source': 'quarterly_financial_report.md', 'department': 'FinSolve Technologies Inc.', 'section': 'Recommendations'})
        elif recommendations_segment[0].strip() and "## Recommendations for 2025" in recommendations_segment[0]:
             temp_chunks.append(recommendations_segment[0].strip())
             temp_metadatas.append({'source': 'quarterly_financial_report.md', 'department': 'FinSolve Technologies Inc.', 'section': 'Recommendations'})

    if len(recs_parts) > 1:
        conclusion_segment = recs_parts[1].split('## Conclusion', 1)
        if len(conclusion_segment) > 1 and conclusion_segment[1].strip():
            temp_chunks.append("## Conclusion\n" + conclusion_segment[1].strip())
            temp_metadatas.append({'source': 'quarterly_financial_report.md', 'department': 'FinSolve Technologies Inc.', 'section': 'Conclusion'})
        elif conclusion_segment[0].strip() and "## Conclusion" in conclusion_segment[0]:
            temp_chunks.append(conclusion_segment[0].strip())
            temp_metadatas.append({'source': 'quarterly_financial_report.md', 'department': 'FinSolve Technologies Inc.', 'section': 'Conclusion'})

    chunks.extend(temp_chunks)
    metadatas_new.extend(temp_metadatas)

texts = [c for c in chunks if c.strip()]
ids = [f"doc_chunk_{i+1}" for i in range(len(texts))]
metadatas = metadatas_new[:len(texts)]

client = chromadb.Client()

collection_name = "finsolve_2024_finance"
ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")

collection = client.get_or_create_collection(
    name=collection_name,
    embedding_function=ef
)


print(f"Inserting {len(texts)} documents into collection '{collection_name}'...")
collection.add(
    ids=ids,
    documents=texts,
    metadatas=metadatas
)
print("Insertion complete.")

query_text = "What were the marketing spend and vendor costs in Q2 2024?"

results = collection.query(
    query_texts=[query_text],
    n_results=1
)

print("\n--- Chroma Query Results Simulation ---")
print(f"Query: {query_text}")
print("---")

if results and results['documents']:
    document_match = results['documents'][0][0]
    metadata_match = results['metadatas'][0][0]

    print("Most Relevant Chunk Found:")
    print(f"Section: {metadata_match.get('section')}")
    print(f"Source: {metadata_match.get('source')}")
    print("-" * 20)
    print(document_match)
else:
    print("No relevant results found.")

print("\n--- Mocked 'Picture of DB File' Contents ---")
print(f"Collection Name: {collection_name}")
print(f"Total documents: {collection.count()}")
print("Example Document (Chunk 3 - Q2):")
print(client.get_collection(collection_name).get(ids=['doc_chunk_3'])['documents'][0][:150] + "...")