# -*- coding: utf-8 -*-
"""Marketing Report0Analysis and Metadata

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13mvSYcJMmIan8Uba4Tn2fyWx00pXnp7n
"""

import re
import json
from datetime import datetime

# --- IMPORTANT: Document Content (simulating reading the uploaded file) ---
# The content of the uploaded 'marketing_report_2024.md' is provided below
# as a multiline string for the script to be fully self-contained.
REPORT_CONTENT = """
# Marketing Report for FinSolve Technologies Inc. - 2024

Executive Summary:
-------------------------------------------
2024 was a pivotal year for the Marketing Department at FinSolve Technologies, marked by ambitious campaigns, strategic partnerships, and a focus on increasing customer engagement across digital and physical channels. The department’s efforts resulted in a 20% increase in new customer acquisition, a 15% growth in brand awareness, and enhanced customer loyalty. Despite a competitive market environment, FinSolve Technologies's marketing initiatives proved to be cost-effective, delivering a solid return on investment (ROI) and positioning the company for further expansion.

Year-Over-Year (YoY) Performance:
-------------------------------------------
FinSolve Technologies's marketing team saw a solid year-over-year (YoY) improvement in key performance metrics:
1. **New Customer Acquisition**: A 20% increase in new customers, outpacing the industry average of 10% growth. The increase was primarily driven by targeted digital marketing campaigns and improved brand visibility in new international markets (Asia and Europe).
2. **Brand Awareness**: Brand awareness grew by 15%, supported by high-visibility campaigns and strategic PR efforts.
3. **Customer Engagement**: Engagement rates saw a slight increase of 5%, driven by content marketing and social media efforts. However, this metric remains a focus for improvement, particularly through personalized and AI-driven content strategies for 2025.

Key Metrics and ROI Analysis:
-------------------------------------------
1. **Customer Acquisition Cost (CAC)**: Reduced to $80, down from $100 in 2023, primarily through better targeting and optimization of high-performing channels.
2. **Return on Ad Spend (ROAS)**: 4.5x for digital campaigns, a significant improvement over the 3x in 2023.
3. **Customer Lifetime Value (CLTV)**: $1,200 per customer, driven by both higher conversion rates and improved retention strategies.
4. **Conversion Rate**: 5% across all digital platforms, indicating strong ad targeting and messaging resonance.
5. **Click-Through Rate (CTR)**: 2.5% for paid ads, up from 2% in 2023, due to better-targeted ads and enhanced content.

Recommendations for Improvement:
-------------------------------------------
1. **Enhance Personalization**: Implement AI-driven marketing automation to increase customer engagement and reduce CAC. Personalized offers and content should be central to next year's strategy.
2. **Expand Market Reach**: Focus on untapped markets, particularly in **Latin America**, where FinSolve Technologies’s services have high growth potential.
3. **Optimize Vendor Relationships**: Improve vendor contract terms and increase the use of performance-based incentives to drive better results from external partners.
4. **Focus on Retention**: While new customer acquisition is important, the marketing team should invest more in retaining existing customers through loyalty programs and personalized communication.

Appendices:
-------------------------------------------
Detailed performance charts and marketing analytics reports are included in the appendices, which provide insights into conversion rates, ROI analysis, and market segmentation.
"""


def chunk_document_by_header(document_text):
    """
    Splits the document into chunks based on the markdown header lines (e.g., '---').
    The header lines in this document structure serve as separators for major sections.
    """
    # Regex to find all sections split by the markdown separator line '---'
    # We will split on a newline followed by any title and a line of '---'
    sections = re.split(
        r"\n([A-Za-z\s&-]+):\n-{10,}\n",
        document_text,
        flags=re.MULTILINE | re.IGNORECASE,
    )

    chunks = {}

    # The first element is the content before the first recognized section title
    chunks["Executive Summary"] = (
        sections[0]
        .replace(
            "# Marketing Report for FinSolve Technologies Inc. - 2024\n\nExecutive Summary:",
            "",
        )
        .strip()
    )

    # Subsequent elements come in pairs: (Title, Content)
    for i in range(1, len(sections), 2):
        if i + 1 < len(sections):
            title = sections[i].strip()
            content = sections[i + 1].strip()
            chunks[title] = content

    print(f"--- Document split into {len(chunks)} logical chunks ---")
    return chunks


def generate_executive_insight(chunk_title, chunk_content):
    """
    Simulates calling an LLM to generate a single, high-level executive insight
    and its strategic implication based on the input chunk.
    """
    # Simple rule-based generation for simulation
    if "Year-Over-Year (YoY) Performance" in chunk_title:
        # Focus on the 20% increase in customer acquisition
        insight = f"""
**Executive Insight: {chunk_title}**

* **Core Finding:** New customer acquisition significantly exceeded expectations, achieving a 20% YoY increase, double the industry average. This validates the effectiveness of targeted digital campaigns in Asia and Europe.
* **Strategic Implication:** The current digital campaign strategy is highly effective and should be scaled. Future budget allocation should prioritize these high-performing channels. The low 5% growth in engagement, however, indicates a need to immediately focus resources on retention and deepening relationships with the new customers gained.
"""
    elif "Key Metrics and ROI Analysis" in chunk_title:
        # Focus on the ROAS and CAC improvement
        insight = f"""
**Executive Insight: {chunk_title}**

* **Core Finding:** The financial efficiency of marketing dramatically improved, with CAC dropping from $100 to $80 and ROAS increasing from 3x to 4.5x. The CLTV of $1,200 provides a healthy 15:1 ratio against the new CAC.
* **Strategic Implication:** Marketing spend is yielding exceptionally high returns. The 4.5x ROAS confirms the profitability of the digital ad investment. This data supports an immediate case for increasing the overall marketing budget to accelerate profitable growth and capture greater market share while efficiency remains high.
"""
    elif "Recommendations for Improvement" in chunk_title:
        # Focus on the personalization and market expansion recommendations
        insight = f"""
**Executive Insight: {chunk_title}**

* **Core Finding:** The primary strategic focus for 2025 is shifting from pure acquisition to personalization and geographic expansion. The report recommends implementing AI-driven automation for personalization and aggressively targeting the Latin American market.
* **Strategic Implication:** The marketing and technology teams must collaborate immediately on the personalization initiative, as it directly impacts CAC reduction and engagement goals. Furthermore, a dedicated budget and team structure need to be established for the Latin American expansion to capitalize on the identified high growth potential in that region.
"""
    else:
        insight = f"**Automated Insight for {chunk_title}:** This is a preliminary section. The key takeaway is the overall success and positioning for expansion. (Snippet: {chunk_content[:100]}...)"

    return insight.strip()


def create_metadata(source_file, chunk_title, generated_content, index):
    """
    Generates metadata for the newly created insight.
    """
    # Create a unique ID for the generated artifact
    safe_title = re.sub(r"[^a-z0-9]", "_", chunk_title.lower()).replace("__", "_")
    artifact_id = f"exec_insight_{index}_{safe_title}"

    metadata = {
        "artifact_id": artifact_id,
        "source_document": source_file,
        "source_chunk_title": chunk_title,
        "generated_timestamp": datetime.now().isoformat(),
        "generation_model": "Simulated Executive Insight Generator",
        "content_type": "Strategic Business Insight",
        "word_count": len(generated_content.split()),
        "key_metrics_mentioned": ["CAC", "ROAS", "CLTV", "Acquisition"],
        "target_audience": ["Executive Leadership", "Board of Directors"],
    }
    return metadata


def main():
    source_file_name = "marketing_report_2024.md"

    # 1. Chunk the document
    chunks = chunk_document_by_header(REPORT_CONTENT)

    # Define which chunks to select for generation
    selected_chunks_titles = [
        "Year-Over-Year (YoY) Performance",
        "Key Metrics and ROI Analysis",
        "Recommendations for Improvement",
    ]

    generated_artifacts = []

    # 2. Iterate through selected chunks to generate new content and metadata
    print("\n--- Generating Executive Insights and Metadata for selected chunks ---")

    for i, title in enumerate(selected_chunks_titles):
        if title in chunks:
            chunk_content = chunks[title]

            # Generate new content (Executive Insight)
            new_content = generate_executive_insight(title, chunk_content)

            # Create metadata
            metadata = create_metadata(source_file_name, title, new_content, i + 1)

            generated_artifacts.append(
                {
                    "source_title": title,
                    "generated_insight": new_content,
                    "metadata": metadata,
                }
            )

            # Print a quick preview of the generated artifact
            print(f"\n[Generated Artifact {i + 1}]")
            print(f"Source: {title}")
            print(f"ID: {metadata['artifact_id']}")
            print(f"Core Finding Snippet: {new_content.splitlines()[3].strip()}...")
        else:
            print(
                f"\n[Warning] Could not find chunk for title: {title}. Check the document headers."
            )

    # 3. Output the final metadata list
    print("\n" + "=" * 70)
    print("FINAL METADATA OUTPUT (for the three generated Executive Insights)")
    print("=" * 70)

    # Pretty-print the metadata for the three artifacts
    for artifact in generated_artifacts:
        print(f"\n--- Metadata for Source: {artifact['source_title']} ---")
        # Use json.dumps for clean, readable output
        print(json.dumps(artifact["metadata"], indent=4))

    # Optional: Display one full generated chunk content
    if generated_artifacts:
        print("\n" + "=" * 70)
        print(
            f"FULL EXECUTIVE INSIGHT EXAMPLE ({generated_artifacts[1]['source_title']})"
        )
        print("=" * 70)
        print(generated_artifacts[1]["generated_insight"])


if __name__ == "__main__":
    main()
