# -*- coding: utf-8 -*-
"""Simple Data Normalization Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GOKmgV9kai4pLDixsV3CKjcuP3aWr1UX
"""

import numpy as np
import pandas as pd
from typing import List, Dict, Any

# A simple Python script demonstrating two common normalization steps:
# 1. Min-Max Scaling for numerical data.
# 2. Case Normalization for text data.


def min_max_normalize(data: List[float]) -> List[float]:
    """
    Normalizes a list of numerical data using Min-Max Scaling.
    The formula is: (X - min(X)) / (max(X) - min(X)).
    Scales all values to be within the range [0, 1].
    """
    if not data:
        return []

    # Use numpy array for efficient calculation
    data_array = np.array(data, dtype=float)

    data_min = data_array.min()
    data_max = data_array.max()

    # Handle the edge case where all values are the same (division by zero)
    if data_max == data_min:
        print("Warning: All numerical values are identical. Returning zeros.")
        return np.zeros_like(data_array).tolist()

    normalized_array = (data_array - data_min) / (data_max - data_min)
    return normalized_array.tolist()


def text_case_normalize(data: List[str], target_case: str = "lower") -> List[str]:
    """
    Normalizes text data by converting all strings to a specified case (default: lowercase).
    """
    normalized_texts = []
    if target_case.lower() == "lower":
        for text in data:
            normalized_texts.append(text.lower())
    elif target_case.lower() == "upper":
        for text in data:
            normalized_texts.append(text.upper())
    else:
        # Default to lower if an invalid target is specified
        for text in data:
            normalized_texts.append(text.lower())
    return normalized_texts


def demonstrate_normalization():
    """
    Runs the normalization functions on sample data.
    """
    print("--- 1. Numerical Data Normalization (Min-Max Scaling) ---")

    # Sample data: user scores, ranging from 50 to 950
    numerical_data = [50.0, 150.0, 950.0, 300.0, 500.0, 750.0]
    print(f"Original Numerical Data: {numerical_data}")

    normalized_numbers = min_max_normalize(numerical_data)
    print(f"Normalized (0 to 1):     {normalized_numbers}\n")

    print("--- 2. Text Data Normalization (Case Conversion) ---")

    # Sample data: product names with inconsistent casing
    text_data = ["FinSolve Pro", "finsolve pro", "FINSOLVE Standard", "Basic Account"]
    print(f"Original Text Data: {text_data}")

    normalized_lower = text_case_normalize(text_data, "lower")
    print(f"Normalized (Lowercase):  {normalized_lower}")

    normalized_upper = text_case_normalize(text_data, "upper")
    print(f"Normalized (Uppercase):  {normalized_upper}")


if __name__ == "__main__":
    demonstrate_normalization()
